// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlcore

type Empty struct {
	ID *string `json:"id"`
}

type NewEventData struct {
	Title string  `json:"title"`
	Date  *string `json:"date"`
}
